[package]
name = "pgs_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "pgs_common"

[dependencies]
dotenv = "0.15.0"
postgres = { version = "0.19.4" }
serde = "1.0.152"
