[package]
name = "toes"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "toes"
crate-type = ["cdylib"]
bench = false

[dependencies]
atree = "0.5.2"

[dependencies.pyo3]
version = "0.14.2"
features = ["extension-module"]