[package]
name = "pgs_slothmark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pgs_nodes = { path = "../pgs_nodes" }
pgs_renderer = { path = "../pgs_renderer" }
