name: e2e tests
on:
  push:
      branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose -f docker-compose.tests.yml up -d --build
      - name: chmod
        run: docker-compose -f docker-compose.tests.yml exec -T web chmod a+x tests.sh
      - name: Test
        run: docker-compose -f docker-compose.tests.yml exec -T web ./tests.sh