name: RustAudit
on:
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
jobs:
  security_audit:
    defaults:
      run:
        working-directory: ./rust/toes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}